name: Linnut
favicon: null
layout_spectrum: 0.4632021465804428
typography_spectrum: 0.14436416095122695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.08163182181306183
  lightness: 0.4690439347177744
  saturation: 0.7891633817926049
  rhythmicContrast: 0.3427825071848929
purpose: []
